---
- name: configure load balancer
  hosts: load_balancers
  become: true
  roles:
    - load_balancer

- name: configure application server
  hosts: app_servers
  become: true
  roles:
    - app_server

- name: configure database server
  hosts: db_servers
  become: true
  roles:
    - db_server